# Generated by Django 6.0.2 on 2026-03-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_livesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='enquiry_type',
            field=models.CharField(default='student', max_length=20),
            preserve_default=False,
        ),
    ]
