# Generated by Django 6.0.2 on 2026-03-06 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('announcement', models.TextField()),
                ('std_class', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('post_to', models.CharField(choices=[('Students', 'Students'), ('Parents', 'Parents'), ('Both', 'Both')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
