# Generated by Django 6.0.2 on 2026-03-06 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='facultyannouncement',
            table='faculty_announcement',
        ),
    ]
