# Generated by Django 6.0.2 on 2026-03-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_facultyannouncement_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyannouncement',
            name='std_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='facultyannouncement',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
