# Generated by Django 6.0.2 on 2026-03-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_rename_course_assignment_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='total_marks',
            field=models.IntegerField(),
        ),
    ]
