# Generated by Django 6.0.2 on 2026-03-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_adminguideline'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_id', models.IntegerField()),
                ('enquiry_type', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('session_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
