# Generated by Django 6.0.2 on 2026-03-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_enquiryaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryaction',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
