# Generated by Django 6.0.2 on 2026-03-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_enquiryaction_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryaction',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
