# Generated by Django 6.0.2 on 2026-02-28 07:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('child_name', models.CharField(max_length=100)),
                ('child_class', models.CharField(max_length=50)),
                ('send_to', models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty')], max_length=20)),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('enquiry_type', models.CharField(choices=[('technical', 'Technical Issue'), ('academic', 'Academic Related'), ('fees', 'Fees Related'), ('general', 'General Query')], max_length=50)),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parent_enquiry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='parent_feedback_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_feedback', to='parent.parentenquiry')),
            ],
            options={
                'db_table': 'parent_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
