# Generated by Django 6.0.2 on 2026-03-05 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_assignment_start_date_alter_assignment_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('short', 'Short Notes'), ('long', 'Long Answer'), ('mcq', 'MCQ')], max_length=50)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/questions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='student.assignment')),
            ],
        ),
    ]
