# Generated by Django 6.0.2 on 2026-03-04 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_enquiry_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='feedback_files/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
