# Generated by Django 6.0.2 on 2026-03-16 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_rename_course_assignment_subject_and_more'),
        ('student', '0004_alter_assignment_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='faculty.assignment'),
        ),
        migrations.RemoveField(
            model_name='assignmentquestion',
            name='assignment',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentQuestion',
        ),
    ]
