# Generated by Django 6.0.2 on 2026-03-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_assignmentsubmission_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='answers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
