# Generated by Django 5.2.12 on 2026-03-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_assignmentsubmission_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded')], default='submitted', max_length=20),
        ),
    ]
