# Generated by Django 6.0.2 on 2026-03-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_enquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('completed', 'Completed'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
