# Generated by Django 5.2.12 on 2026-03-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_assignmentsubmission_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='grade',
        ),
    ]
