# Generated by Django 5.2.12 on 2026-03-18 13:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_rename_course_assignment_subject_and_more'),
        ('student', '0008_remove_assignmentsubmission_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
    ]
